name: Terraform Plan and Deployment

on:
  - workflow_dispatch

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  terraform:
    name: Terraform apply
    runs-on: [ubuntu-latest]
    defaults:
      run:
        working-directory: .
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: anibrinja/provision-eks-cluster-terraform
          ssh-key: ${{ secrets.REPOSITORY_SECRET }}
          
      - name: Checking versions
        run: |
          terraform -v
      - name: Identity
        run: |
          aws sts get-caller-identity
      - name: Terraform init
        run: terraform init
      - name: Terraform output module
        run: terraform plan -var-file="values.tfvars"
      - name: Terraform apply
        run: terraform apply --auto-approve -var-file="values.tfvars"
